### ISSUE TITLE
Disable UI and notifications

### ISSUE THREAD

**Issue by pepelsbey** [shower/cli#15]
I doubt anyone needs BrowserSync’s UI page and “Browsersync: connected” message every time page opens or reloads. Options to disable:

```
ui: false,
notify: false
```
<img width="318" alt="screenshot 2018-09-20 at 16 41 10" src="https://user-images.githubusercontent.com/105274/45822422-1bd84300-bcf4-11e8-8480-b120fe46f7a2.png">

**Comment by nikolay-govorov** [comment]
I want to add flag '--ui' and by default using false

**Comment by pepelsbey** [comment]
Is there a use case for UI?

**Comment by nikolay-govorov** [comment]
I am comfortable to see that the browser sync did not fall off

**Comment by nikolay-govorov** [comment]
Yes, I understand your pain. I will remove popup in next release. It will be ready on this weekend.

**Comment by pepelsbey** [comment]
No rush :) I’ve been just thinking if UI option (even disabled by default) is something even worth keeping among available options. I mean, is “BS is still alive” knowledge that valuable? Also: what BS is doing in my browser, I’m using Shower now!

**Comment by nikolay-govorov** [comment]
By default UI and notify is disabled in `0.2.3` version
