### ISSUE TITLE
Project and template code style

### ISSUE THREAD

**Issue by pepelsbey** [shower/cli#16]
It’s different from the one used in [shower-core](https://github.com/shower/core)’s JS, [shower](https://github.com/shower/shower)’s and [theme’s](https://github.com/shower/ribbon/blob/master/index.html) HTML. Mostly it’s 2 spaces vs. 4 spaces difference, but HTML is also formatted in a different way.

I’d keep it consistent throughout the whole project, if you don’t mind. Because now when I run `shower create` I see your code style, not Shower’s one.

**Comment by nikolay-govorov** [comment]
Yes, it will be correct

**Comment by nikolay-govorov** [comment]
Fix in `0.2.3` version
