### ISSUE TITLE
Update paths for template and themes

### ISSUE THREAD

**Issue by pepelsbey** [shower/cli#21]
We’re in the process of moving packages from `shower-package` to `@shower/package` structure. The latest theme releases are already published exclusively to `@shower/ribbon` and `@shower/material`. Shower’s gulpfile is also [got updated accordingly](https://github.com/shower/shower/commit/82712d4ca3d9a4fbcc4ec2999d188f869f2efa6f) to prepare && archive properly.

I guess shower-cli needs the same update.

**Comment by nikolay-govorov** [comment]
Wow, great! I will update the CLI for the new package structure. I understand correctly that the packages under the old names will not be updated?

**Comment by pepelsbey** [comment]
Yep, that’s the plan: eventually deprecate all `shower-package` packages, meanwhile not to update them. Because it’s just complicated thing to do.

**Comment by pepelsbey** [comment]
Currently, the latest versions of Ribbon and Material themes are published [under @shower org](https://www.npmjs.com/package/@shower/ribbon), but I haven’t found a place where I can update paths. So there are two ideas:

1. It’s time to update `shower-ribbon` and `shower-material` to `@shower/ribbon` and `@shower/material`
2. I wonder if it would be better to explicitly list them as dependencies in package.json, [just like shower package does](https://github.com/shower/shower/blob/master/package.json#L30-L32).

**Comment by pepelsbey** [comment]
Will you have some time to work on this? Let me know if I can help in any way.

**Comment by pepelsbey** [comment]
There you go: #21
