### ISSUE TITLE
Using with NPX

### ISSUE THREAD

**Issue by avdeev** [shower/cli#3]
Can we use shorter command for creating new slides?

`npx shower/cli create my-slides`

Inspired by [CRA](https://github.com/facebook/create-react-app)

**Comment by nikolay-govorov** [comment]
Hi. We can add aliases for commands like 'c' for 'create', ' s' for 'serve', 'p' for 'pdf'.

**Comment by nikolay-govorov** [comment]
The `npx shower-cli create my-slides` command works fine. Or is it about something else?

**Comment by avdeev** [comment]
Can we add this method to the documentation? Like CRA.

![image](https://user-images.githubusercontent.com/1241671/41095212-6f7d7720-6a59-11e8-8ac7-1f7b823efc6d.png)

**Comment by nikolay-govorov** [comment]
@avdeev, yes, I think it will be convenient
