### ISSUE TITLE
Add flag `--yes` from `create` task, which will select all default parameters

### ISSUE THREAD

**Issue by nikolay-govorov** [shower/cli#33]

**Comment by kostyabushuev** [comment]
hello
i would like to try to implement this feature, but i have two question
What parameters are called by default? 
Why we cannot use '--default' flag instead of '--all'

**Comment by nikolay-govorov** [comment]
Hey. Thank you for wanting to help.

Now the create command at startup shows a dialog box with a suggestion to choose the aspect ratio and theme. These parameters are likely to become more.

Since the parameters are chosen for the most common cases, you can almost always just create a presentation. To do this, it is proposed to add the flag `--yes` (with aliases `-y`), which will simply answer all questions by default.

The flag is called `--yes` because its semantic meaning is to answer `Yes`to all questions. So, for example, behave `npm`, `yarn` and `eslint` on the command `init`.
