### ISSUE TITLE
Theme creation mechanism

### ISSUE THREAD

**Issue by avdeev** [shower/cli#5]
Can we add here the possibility of creating themes?

**Comment by nikolay-govorov** [comment]
Is it about creating your own themes or switching existing ones?

**Comment by avdeev** [comment]
Creating :)

It would be very convenient for the community. I think, this feature could be implemented in this CLI.

Here was a small discussion with @pepelsbey:
https://github.com/shower/shower/issues/315

Now the creation of a theme is not a very convenient process. :(
It is not automated, there are many things to guess.
I tried to create my own theme and publish it in some shower awesome list, but it turned out that it's easier to break styles in the existing.

**Comment by pepelsbey** [comment]
@avdeev have you tried new updated themes? Vanilla CSS themes now have a bit simpler structure, less dependencies and better API. There’s still no proper template for that, but I’ll look into that next week.

**Comment by avdeev** [comment]
@pepelsbey Ok, thanks! I'll try.

It would be great to have a simple base supportable and updatable template for a new theme.
And be able to simply switch/add a theme to the presentation.
And publish a new theme to the registry/list. :)

**Comment by nikolay-govorov** [comment]
If we can define the template structure for the theme, we can add the `--theme` flag to the create command.

**Comment by pepelsbey** [comment]
You know, I tried it twice and couldn’t come up with something universal enough to start your own theme. I don’t want to infulence new themes anymore. That’s why I’d rather create a couple of new ones that are completely (or at least drastically) different from existing ones.

That’d give people an idea that they could basically create anything they want. I’m closing this issue for now. Let’s see how this alternative themes idea will go.
