### ISSUE TITLE
commands don't work on windows 10

### ISSUE THREAD

**Issue by greatstudentkaze** [shower/cli#56]
I installed the shower-cli and shower globally. When I want to create a presentation by `shower create` it doesn't happen.

![image](https://user-images.githubusercontent.com/105274/111025290-3044b480-83f4-11eb-80e4-7024b708d49a.png)

Other commands have the same
PowerShell has the same as cmd

**Comment by pepelsbey** [comment]
Quoting the #374 by @lenaryan

> Slides are not creating with "shower create". Looks like my code editor is "thinking" but nothing happens.
Win 10, VSCode.

![image](https://user-images.githubusercontent.com/105274/127308607-0d1c1c8b-f3a8-44b2-8cb6-b0a29cf27e14.png)

**Comment by speker2010** [comment]
> It's the same for me. I installed the package with `npm install --global @shower/cli`. Then I tried to execute `shower create <name>` in VS Code terminal, but I got an error "shower: Невозможно загрузить файл ...\npm\shower.ps1, так как выполнение сценариев отключено в этой системе". Then I tried the same in WebStorm terminal, because it uses something of its own instead Windows Power Shell. And it worked - the first and only time. The project was created. But I was interested in solving the problem in VS Code, so I deleted the newly created project (without closing WebStorm - I don't know if it matters). And then I opened Windows Power Shell as administrator and changed policy with `Set-ExecutionPolicy unrestricted`. After that no attempt to execute `shower create <name>` leads to any discernible results. I tried to uninstall and reinstall the cli, to reboot the PC, to use `shower create <name>` in Power Shell itself – these did not help. I tried to do the same on another PC (also under Windows 10), but nothing worked there from the very beginning, even in WebStorm.

Try uppercase first letter in "unrestricted" in `Set-ExecutionPolicy unrestricted`. 

I tried set "Restricted", then I installed shower, and `shower create test` showed me errors. 

After that, I executed `Set-ExecutionPolicy Unrestricted` and `shower create test` worked fine

**Comment by pepelsbey** [comment]
@nikolay-govorov that was quick! Thank you :) Is it ready to be release right away?

**Comment by nikolay-govorov** [comment]
Hello. Thank you for the report and help in debugging the problem.

The fix will be is available in next version v0.3.1.
