### ISSUE TITLE
Run commands directly for easy automatisation

### ISSUE THREAD

**Issue by igsekor** [shower/cli#57]
My suggestion is dealing with an issue to run commands in terminal without any steps to setup slides.

Shower CLI is pretty good interface to create and manage a presentation! I was absolutely happy with this tool any time before. But...

I want to build up a new layer under Shower CLI. It will be an extension for VS Code for managing a presentation in this IDE. I want to use Shower CLI for commands but it is impossible. I'll try to describe on an example of one command for clarification. Command `shower create` is constructed as a master for own settings and fast command for default settings. It will be much more relevant to my case if `shower create` will be able to setup theme and ratio via parameters, e.g. `--theme` and `--ratio`. It will be suitable for any cases are connected with bash scripts and any high-level tools based on Shower CLI as my own.

I will be happy to become a contributor to make this feature. Also I'm thinking seriously about support of any other repository's issues in the list. I'm trying to be useful.

Is it possible to answer me on suggestion which I've described above?

@nikolay-govorov @pepelsbey

**Comment by pepelsbey** [comment]
I think it’s a good idea to expose the same features via parameters. It might also help if you always create your slides with 16:9 and Ribbon options. You could just get something like `shower create --ratio 16:9 --theme ribbon` from your CLI history or make an alias.

**Comment by igsekor** [comment]
To be sure that user want to override a folder, it will be good to add `--override` option. @nikolay-govorov and @pepelsbey , is it good idea?

**Comment by nikolay-govorov** [comment]
It will be in the next release
