### ISSUE TITLE
Rename installed package to shower

### ISSUE THREAD

**Issue by pepelsbey** [shower/cli#7]
Just like many CLI tools do: `grunt-cli` becomes `grunt`, the same applies to Gulp and many others. It’s much easier to type `shower` instead of `shower-cli`.

**Comment by nikolay-govorov** [comment]
The name of the shower is [already occupied](https://www.npmjs.com/package/shower). It is used by the [main repository](https://github.com/shower/shower).

**Comment by nikolay-govorov** [comment]
I understand what you mean. We can add the shower-cli to the shower and use the CLI from there

**Comment by pepelsbey** [comment]
Hmm, I don’t think you do :) I’m pretty shure there’s a way for shower-cli to be available as shower command in console once it’s installed. I’m not talking about shower npm package, I’m talking about shower alias in console. When you install gulp-cli it becomes available under gulp alias. I’d like shower-cli to do the same.

**Comment by nikolay-govorov** [comment]
What's the problem then? Now there is a package `shower-cli`. After n is installed, the `shower` command is available from the console. I can run it `$ shower --help`.

**Comment by pepelsbey** [comment]
```
/Users/pepelsbey/.nvm/versions/node/v10.9.0/lib
├── npm@6.4.0
├── shower-cli@0.1.1
…
$ shower
bash: shower: command not found
```

**Comment by nikolay-govorov** [comment]
Oh, shit. This is a bug in version 0.1.1. Thanks, I'll fix it.

**Comment by nikolay-govorov** [comment]
Fixed it. Please, update package
