### ISSUE TITLE
Does the cli need the publish function?

### ISSUE THREAD

**Issue by nikolay-govorov** [shower/cli#9]

**Comment by avdeev** [comment]
Why not. :)
We can move all functions to CLI, like in Create React App or Vue CLI.

**Comment by pepelsbey** [comment]
Yep, I’d rather have all service functions in one place:

- prepare
- archive
- publish
- pdf
- etc.

That’d serve two main use cases:

1. Pro users would have everything they need globally available from a console.
2. Occasional users would still fork the main repository and use npm scripts.

I’d still sit down with all interested parties and discuss Shower infrastructure. That might be a quick call where we could discuss what to keep in the main repository, what and how to publish shwr.me themes showcase. Let me know if you’re interested :)

**Comment by nikolay-govorov** [comment]
Implemented since version 2.0.0-1
